import config from '@/configs/config'

var API_ROOT = config.API_ROOT

export default {
  login: `${API_ROOT}/index/login/login`,
  register: `${API_ROOT}/index/login/reg`,
  resetPsw: `${API_ROOT}/index/login/repsw`,
  getCode: `${API_ROOT}/index/code/getcode`,
  getRoomList: `${API_ROOT}/index/room/rtlist`,
  getIndex: `${API_ROOT}/index/room/index`,
  getChildrenRoomList: `${API_ROOT}/index/room/rlist`,
  getShopList: `${API_ROOT}/index/store/lists`,
  getChatRoom: `${API_ROOT}/index/chat/lists`,
  getFriend: `${API_ROOT}/index/friend/friend`,
  handleFriend: `${API_ROOT}/index/friend/handle`,
  getUserInfo: `${API_ROOT}/index/user/info`,
  getRank: `${API_ROOT}/index/rank/lists`,
  getTask: `${API_ROOT}/index/task/lists`,
  getReward: `${API_ROOT}/index/task/get`,
  getNews: `${API_ROOT}/index/news/lists`,
  getNewsDetail: `${API_ROOT}/index/news/detail`,
  getFriendInfo: `${API_ROOT}/index/friend/info`,
  buy: `${API_ROOT}/index/store/buy`,
  getService: `${API_ROOT}/index/basic/getkf`,
  modifyName: `${API_ROOT}/index/user/savename`,
  modifyPsw: `${API_ROOT}/index/user/uppsw`,
  modifyPayPsw: `${API_ROOT}/index/user/uppaypsw`,
  referrals: `${API_ROOT}/index/user/uprec`,
  addFriend: `${API_ROOT}/index/friend/add`,
  deleteFriend: `${API_ROOT}/index/friend/del`,
  addPraise: `${API_ROOT}/index/friend/praise`,
  gift: `${API_ROOT}/index/friend/give`,
  enterRoom: `${API_ROOT}/index/room/in`,
  leaveRoom: `${API_ROOT}/index/room/out`,
  createRoom: `${API_ROOT}/index/room/create`,
  getBanner: `${API_ROOT}/index/index/index`,
  sendRedBag: `${API_ROOT}/index/redbag/post`,
  openRedBag: `${API_ROOT}/index/redbag/get`,
  getRedBagReco: `${API_ROOT}/index/redbag/lists`,
  inOutReco: `${API_ROOT}/index/user/income`,
  hbInfo: `${API_ROOT}/index/redbag/info`,
  give: `${API_ROOT}/index/redbag/settle`,
  getSpeaker: `${API_ROOT}/index/store/horn`,
  roomSpeak: `${API_ROOT}/index/room/speak`,
  recharge: `${API_ROOT}/index/recharge/pay`,
  exchange: `${API_ROOT}/index/user/exchange`,
  reward: `${API_ROOT}/index/redbag/reward`,
  getTeamMembersInfo: `${API_ROOT}/index/room/userlist`,
  getExchange: `${API_ROOT}/index/basic/getexchange`,
  removeTeamMember: `${API_ROOT}/index//room/tick`,
  checkVer: `${API_ROOT}/index/version/check`,
  getLastRedBag: `${API_ROOT}/index/redbag/baglist`,
  getQrCode: `${API_ROOT}/index/basic/getqrcode`,
  remark: `${API_ROOT}/index/friend/upremark`,
  numberRange: `${API_ROOT}/index/basic/getroomnumber`,
  backCheck: `${API_ROOT}/index/agency/index`,
  resetPayPsw: `${API_ROOT}/index/user/repaypsw`,
  wxLogin: `${API_ROOT}/index/login/wxlogin`
}